apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "career-koala.fullname" . }}-api
  namespace: {{ include "career-koala.namespace" . }}
  labels:
    {{- include "career-koala.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.api.env }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
