apiVersion: v1
kind: Secret
metadata:
  name: {{ include "career-koala.fullname" . }}-api
  namespace: {{ include "career-koala.namespace" . }}
  labels:
    {{- include "career-koala.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $val := .Values.api.secret }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
