namespace:
  create: true
  name: "career-koala"

api:
  image:
    repository: ""
    tag: ""
  waitForPostgres: false
  waitForMigrations: true
  env:
    ENABLE_AI: "false"
    MODEL_NAME: ""
    VALIDATE_MODEL: "false"
    GOOGLE_CLOUD_PROJECT: ""
    VERTEX_LOCATION: ""
    POSTGRES_HOST: ""
    POSTGRES_PORT: ""
    POSTGRES_USER: ""
    POSTGRES_DB: ""
    POSTGRES_SSLMODE: ""
  secret:
    POSTGRES_PASSWORD: ""
    POSTGRES_DATABASE_URL: ""
ui:
  image:
    repository: ""
    tag: ""
  env:
    API_BASE: ""

ingress:
  enabled: true
  host: ""
  tls:
    enabled: false
    secretName: ""

postgresql:
  enabled: false
  auth:
    username: ""
    password: ""
    database: ""

migrations:
  backoffLimit: 5
  ttlSecondsAfterFinished: 3600
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent
  waitForPostgres: false
